version: "3.9"

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: flask-mailhog-web
    environment:
      - MAIL_SERVER=mailhog
      - MAIL_PORT=1025
      - DB_HOST=mysql-db
      - DB_USER=flaskuser
      - DB_PASSWORD=flaskpass
      - DB_NAME=emailsdb
    depends_on:
      - mailhog
      - mysql-db
    networks:
      - my-bridge-network

  mailhog:
    build:
      context: /Users/layannasereddin/test-task
      dockerfile: Dockerfile
    container_name: mailhog
    command: ["MailHog", "-auth-file=/auth/pass"]
    volumes:
      - ./auth:/auth
    networks:
      - my-bridge-network

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=emailsdb
      - MYSQL_USER=flaskuser
      - MYSQL_PASSWORD=flaskpass
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my-bridge-network

networks:
  my-bridge-network:
    external: true

volumes:
  mysql_data:

